### ISSUE TITLE
Environmental Tech Crystal Laser Lens

### ISSUE THREAD

**Issue by DanielGalrito** [End-of-Days-Modpack-Team/Synthesis#11]
In a new version of ET, new laser lens were introduced which allow the Void Ore Miner to produce the crystals needed for higher tiers at a higher chance, but it requires a reset to the void miner's configs.

https://www.reddit.com/r/feedthebeast/comments/7mcs32/new_environmental_tech_update_for_112_includes/

**Comment by jc2xs** [comment]
Implemented in version 1.3.1 of the pack
