### ISSUE TITLE
V 1.3.1 Fails to load

### ISSUE THREAD

**Issue by LogicFalls** [End-of-Days-Modpack-Team/Synthesis#14]
Quite simply. After starting up, a few seconds later it crashes and produces a large list of bad mods.

**Comment by Fortanono** [comment]
Um, crash report? We can't help you if we don't know what is going on technically.

**Comment by LogicFalls** [comment]
I'd provide one if there was one to provide. Although, after looking at the crash screen a little closer, it seems Forge thinks that every single mod is duplicated. I've not edited the pack at all.

**Comment by Fortanono** [comment]
Have you gone into the crash-logs folder in your minecraft instance?

**Comment by LogicFalls** [comment]
I have 16, with 10 Given to Minecraft.
Yes, I checked there. No crash report was generated.

**Comment by jc2xs** [comment]
This sounds like curse/twitch didn't update the pack correctly and there by didn't delete mods it should have during the update.  Can you try to install a new instance of the pack?

**Comment by LogicFalls** [comment]
I'll try that, but looking through manually it looked as it should.

**Comment by jc2xs** [comment]
No issues and I think we all here try to help as best as we can.
