### ISSUE TITLE
[Enhancement] Use Pam's Rye to make Earthworks thatch

### ISSUE THREAD

**Issue by Fortanono** [End-of-Days-Modpack-Team/Synthesis#3]
Quark thatch is made with 4 wheat, as is Earthworks thatch. However, Quark thatch and Earthworks thatch have two completely different artstyles. Quark's is closer to vanilla wheat, while Earthworks has a more subtle color and fine texture, somewhat like Pam's rye. So I feel this would be an elegant solution to this problem.

**Comment by jc2xs** [comment]
I'll include this in the next patch.  But it sounds like a good idea.

**Comment by jc2xs** [comment]
Fixed in the latest version of the pack which should be released to Twitch/CurseForge later today.
