### ISSUE TITLE
Uncraftable Ultimate Singularity

### ISSUE THREAD

**Issue by MrDee01** [End-of-Days-Modpack-Team/Synthesis#6]
The Ultimate Singularity, used in some endgame recipes, is not craftable, as it requires tungesten, titanium, chrome, brass and zinc singularities. None of these can be crafted because no mod in the pack adds any of these ingots.

**Comment by jc2xs** [comment]
Talked with Boqzo about this.  He is going to do some more scripting to fix this issue.

**Comment by jc2xs** [comment]
Fixed in the latest dev
